### ISSUE TITLE
[Feature request] Add JavaZonedDateTimeAdapter

### ISSUE THREAD

**Issue by leinardi** [apollographql/apollo-kotlin-adapters#21]
Currently there are adapters for the `java.time` `Instant`, `LocalDate`, `LocalDateTime`, `LocalTime` and `OffsetDateTime` but one for the `ZonedDateTime` is missing.

Such adapter is necessary when you need to parse something that contains the IANA time zone identifier, like for example `1987-07-08T08:10+02:00[Europe/Prague]`.

Something like this:

```kotlin
/**
 * An [Adapter] that converts a date and time to/from [java.time.ZonedDateTime]
 *
 * Examples:
 * - "2010-06-01T22:19:44.475Z"
 * - "2010-06-01T23:19:44.475+01:00"
 * - "2010-06-01T23:19:44.475+02:00[Europe/Prague]"
 *
 */
object JavaZonedDateTimeAdapter : Adapter<ZonedDateTime> {
    override fun fromJson(reader: JsonReader, customScalarAdapters: CustomScalarAdapters): ZonedDateTime {
        return ZonedDateTime.parse(reader.nextString()!!)
    }

    override fun toJson(writer: JsonWriter, customScalarAdapters: CustomScalarAdapters, value: ZonedDateTime) {
        writer.value(value.format(DateTimeFormatter.ISO_ZONED_DATE_TIME))
    }
}
```

If you agree with this feature request, I'd be happy to create a PR to address it. Let me know.

**Comment by martinbonnin** [comment]
Time APIs never cease to amaze! That'd be a great addition, a PR would be very welcome 👍

**Comment by leinardi** [comment]
Yeah, [dealing with date and times is always crazy](https://www.youtube.com/watch?v=-5wpm-gesOY) :sweat_smile: 

PR created! #22
