### ISSUE TITLE
BigDecimal printed as object reference in cache dump

### ISSUE THREAD

**Issue by jvanderwee** [apollographql/apollo-kotlin-adapters#28]
Apologies if I'm raising this in the wrong repo! We're using `BigDecimalAdapter` like so:

```
        mapScalar(
            graphQLName = "Decimal",
            targetName = "com.apollographql.adapter.core.BigDecimal",
            expression = "com.apollographql.adapter.core.BigDecimalAdapter",
        )
```

When we print the cache dump like so:

```
val dump = apolloClient.apolloStore.dump()
println(NormalizedCache.prettifyDump(dump))
```

then our Decimal fields are printed as `JsonNumber` object references e.g.:
```
grossAmount: com.apollographql.apollo.api.json.JsonNumber@18984d68
```

**Comment by martinbonnin** [comment]
Ah, sorry, I meant do you want to open the PR to do so? 

You have the use case so you'll know better what format to use + free internet points! No worries if not, just let us know.
