### ISSUE TITLE
Question: StringAdapter and KtorHttpUrlAdapter

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin-adapters#8]
Is there a migration destination for StringAdapter and KtorHttpUrlAdapter in this repository?
Or should I continue using com.apollographql.apollo?

**Comment by martinbonnin** [comment]
`StringAdapter` is a core adapter and is still part of the main repository (`com.apollographql.apollo.api.StringAdapter`). 

`KtorHttpUrlAdapter` is now part of `apollo-kotlin-ktor-support`. It's at `com.apollographql.ktor.adapter.KtorHttpUrlAdapter`

**Comment by sonatard** [comment]
Thank you!

https://github.com/apollographql/apollo-kotlin-ktor-support
